
locale: "zh"
title: "SunKatrina盼盼's Blog"       
description: '尝一口人间果，走一遭人生路'
url: "https://sunsipan,github.io"
teaser: "assets/blogimg/earth.jpg"

timezone: Asia/Shanghai          
markdown: kramdown          
highlighter: rouge
excerpt_separator: <!--more-->
permalink:         /:year/:month/:title/
timezone:          Asia/Shanghai



kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  enable_coderay: false  

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"



sass:
  sass_dir: _sass
  style: compressed

  
  
owner:
  name: SunKatrina盼盼
  avatar: avatar.jpg
  job: "python"
  bio: "尝一口人间果，走一遭人生路"
    
  github: sunsipan #username
  weibo: pp199706
  facebook:  #username
  email: 1635707508@qq.com
  duoshuo:  #多说域名

  google:
    plus: #username
    analytics: UA-62251910-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  disqus-shortname: #username
  twitter:  #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  flickr: #username
  codepen: #username
  # reading files
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

    
include:
   - .htaccess
   - _pages
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
  
